CREATE ROLE IF NOT EXISTS skye WITH LOGIN PASSWORD 'your_password';
CREATE DATABASE IF NOT EXISTS skye OWNER skye;
CREATE EXTENSION IS NOT EXISTS pg_tgrm;

CREATE TABLE IF NOT EXISTS prefix(
    prefix TEXT
);

CREATE TABLE IF NOT EXISTS logs (
    channel_id BIGINT
);